basePath: /analytics/v1
definitions:
  models.Counter:
    properties:
      count:
        example: 5
        type: integer
    type: object
  models.SummaryTime:
    properties:
      duration:
        example: 1005
        type: integer
      task_id:
        description: TODO поменять на реальный пример
        example: test123
        type: string
    type: object
host: localhost:3003
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Analytics server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Analytics API
  version: "1.0"
paths:
  /approved_tasks:
    get:
      description: endpoint return count of approved tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Counter'
      summary: get count of approved tasks
  /declined_tasks:
    get:
      description: endpoint return count of declined tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Counter'
      summary: get count of declined tasks
  /summary_time:
    get:
      description: Return task id and summary time of decision in seconds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SummaryTime'
            type: array
      summary: Get summary time for each task
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
